name: Deploy to Itch.io

on:
  push:
    branches:
      - main # Change this if your default branch is 'master'

jobs:
  export-and-publish:
    name: Web Export & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Export Godot Project
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_version: "4.6.2"
          relative_project_path: "./" # Change this if your project.godot is inside a subfolder
          archive_output: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Itch.io via Butler
        uses: manleydev/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html
          ITCH_GAME: courier
          ITCH_USER: poorcoco
          PACKAGE: ${{ steps.export.outputs.archive_directory }}/Web.zip